name: test_bazarr_execution
on: workflow_dispatch

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      ROOT_DIRECTORY: .
      SCRIPTS_DIRECTORY: .github/scripts
      FETCH_DEPTH: 15 # Should be enough
    steps:
      - name: Validate branch
        if: ${{ github.ref != 'refs/heads/development' }}
        run: |
          echo This action can only be run on development branch, not ${{ github.ref }}
          exit 1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
          ref: development

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: "${{ env.UI_DIRECTORY }}/.nvmrc"

      - name: Install UI Dependencies
        run: npm install
        working-directory: ${{ env.UI_DIRECTORY }}

      - name: Build UI
        run: npm run build
        working-directory: ${{ env.UI_DIRECTORY }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.25"  # Best practice: pin uv version
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Test Bazarr execution
        run: |
          bash '${{ env.SCRIPTS_DIRECTORY }}/build_test.sh'
